import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { ColorModeButton } from "@/components/ui/color-mode";
import { StrictMode } from "react";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Provider } from "@/components/ui/provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="light" style={{ colorScheme: "light" }}>
			<head>
				<link
					href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
					rel="stylesheet"
				/>
			</head>
			<body>
				<NextIntlClientProvider>
					<Provider>
						<StrictMode>{children}</StrictMode>

						<ReactQueryDevtools initialIsOpen={false} position="bottom" />

						<ColorModeButton style={{ position: "fixed", right: 0, top: 0 }} />
					</Provider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
